version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run:
          name: Update NPM
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: 'npm install'  
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test Action
          command: 'npm test'
  deploy:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - run: 
        - name: Deploy to Glitch
        - command: 'glitch-deploy'


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build